Запрос на добавление ветки с пересобранной структурой проекта
ViRGiL175/java-diner-automation pull request #77
Opened 2020-10-24 18:35 UTC by EsQLap

Проект пересобран в соответствии со стандартами Gradle и Idea

2020-10-24 19:59 UTC, ViRGiL175 requested changes
Не все в порядке.

2020-10-24 19:59 UTC, ViRGiL175 commented on .gitignore
> +.idea/
Зачем? В стандартном gitignore же такого нет.

2020-10-24 19:59 UTC, ViRGiL175 commented on java-dinerautomation/src/main/java/ru/commandos/Humans/Barmen.java
> +        Logger.debug("ингредиентов осталось в баре: " + bar.checkIngredients());
Нужная правка?

2020-10-24 19:59 UTC, ViRGiL175 commented on java-dinerautomation/src/main/java/ru/commandos/Humans/Cook.java
> +        Logger.info("ингредиентов осталось на кухне: " + kitchen.checkIngredients());
Скорее всего ошибочно.

2020-10-25 04:10 UTC, EsQLap commented on .gitignore
> +.idea/
Без неё отслеживаются 7-8 файлов .xml в папке .idea, отвечающих за конфигурацию собранного проекта

2020-10-25 04:12 UTC, EsQLap commented on java-dinerautomation/src/main/java/ru/commandos/Humans/Barmen.java
> +        Logger.debug("ингредиентов осталось в баре: " + bar.checkIngredients());
К сожалению, не нужная. Осталась после нашего дм. Исправлю следующим коммитом в этой ветке

2020-10-25 09:09 UTC, ViRGiL175 commented on .gitignore
> +.idea/
Если это официальный всеми используемый `.gitignore`, то значит так и нужно. 

Ты же не знаешь конфигурацию IDEA, сейчас заигнорил наобум. А `.gitignore` писали специалисты, и пользовалось им полмира. 

Или были какие-то проблемы с конфигурацией, пока не заигнорил?

2020-10-25 09:13 UTC, ViRGiL175 commented on .gitignore
> +.idea/
![image](https://user-images.githubusercontent.com/11541555/97103077-cdac7f80-16c3-11eb-9692-673685a7d00f.png)

Зачекаутился на фиксовую ветку, ничего не собирается.

2020-10-26 13:13 UTC, ViRGiL175 commented
Импорты не подхватываются. Сам посижу с этим.

2020-10-26 13:41 UTC, ViRGiL175 commented
![image](https://user-images.githubusercontent.com/11541555/97179589-6de0d200-17b2-11eb-977b-f9ae399a644b.png)

2020-10-26 13:57 UTC, EsQLap commented
> Импорты не подхватываются. Сам посижу с этим.

Это очень странно, потому что вчера у Тани после дм всё без проблем запустилось

2020-10-26 15:21 UTC, ViRGiL175 commented
Вы вообще не использовали плагин Gradle для сборки executable приложений. Хз, как jar была собрана и запущена, опять, видимо, не Грэддлом, а каким-то левыми средствами IDEA.

2020-10-26 15:42 UTC, ViRGiL175 commented
Залил свою ветку https://github.com/ViRGiL175/java-diner-automation/tree/fix_gff_rebuild_structure

1. Корректный `.gitignore`, который не учитывает только релизную для джарок папку, в которой архив
    1. Игнорирует `libs`, ибо так всегда делают, это внешние зависимости. Нужно класть вручную и не заливать в репозиторий
1. Корректная структура проекта 
1. Корректный Gradle-плагин application для сборки исполняемых приложений, настроил его
1. Перегнал все кодировки вручную в UTF-8 без BOM, выставил дефолтную для проекта UTF-8
1. Добавил прямо в проект конфиг запуска Main

Проверьте.

2020-10-26 15:43 UTC, ViRGiL175 commented
Плагин для выполняемых приложений: https://docs.gradle.org/current/userguide/application_plugin.html

2020-10-26 18:19 UTC, EsQLap commented
Закрываем, мерджить будем с веткой fix_gff_rebuild_structure

2020-10-26 18:19 UTC, closed without merging